include:
  - ../wazuh-docker/single-node/docker-compose.yml
#  - ../CTFd/docker-compose.yml

services:
  web:
    image: nginx
    ports:
      - 8001:80
    volumes:
      - ./src:/usr/share/nginx/html
  network_monitor:
    image: jasonish/suricata:7.0.3
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes: 
      - ./logs:/var/log/suricata
      - ./etc:/etc/suricata
    environment:
      - SURICATA_OPTIONS=-i eth0
    network_mode: service:web
  wazuh.agent:
    build:
      context: ./wazuh_agent/
      dockerfile: Dockerfile
    depends_on:
      - wazuh.manager
    volumes:
      - ./logs:/var/log/suricata:ro